functional:
  - Пользователь может зарегистрироваться через GitHub OAuth
  - Пользователь может создать игру (против бота, случайного соперника или друга)
  - Пользователь может выбирать задачи из каталога с фильтрацией по сложности и тегам
  - Система предоставляет веб-редактор кода с подсветкой синтаксиса для выбранного языка
  - Система автоматически проверяет решение через тесты и показывает результат
  - Пользователь видит свой рейтинг (ELO), статистику игр и прогресс
  - Пользователь может участвовать в турнирах с призовой системой рейтинговых очков
  - Пользователь может общаться с соперником в чате во время игры

non-functional:
  - Время ответа системы на действия пользователя (создание игры, отправка решения) не должно превышать 2 секунд
  - Система должна поддерживать до 5000 одновременных активных игр
  - Доступность системы (uptime) должна составлять не менее 99.5%
  - Код пользователя должен выполняться в изолированных Docker-контейнерах для безопасности
  - Интерфейс должен корректно работать в последних версиях Chrome, Firefox, Safari и Edge
  - Мобильная версия интерфейса должна быть адаптивной для экранов от 320px
  - Данные игр и решений должны сохраняться в надежном хранилище с регулярным бэкапом

implicit:
  - Интерфейс должен быть интуитивно понятен для программистов разного уровня (от новичков до экспертов)
  - Система должна поддерживать здоровую конкурентную среду без возможности читерства
  - Все пользовательские данные (особенно код решений) должны быть конфиденциальны
  - Система должна быть расширяемой для добавления новых языков программирования и типов задач
  - Сообщество должно иметь возможность создавать и публиковать свои задачи через GitHub
  - Интеграция с GitHub должна использовать стандартные OAuth-протоколы без хранения паролей
