functional:
  - "Пользователь может зарегистрироваться через GitHub OAuth (обязательное условие для создания игры)"
  - "Пользователь может создать игру в разных режимах: против бота, случайного соперника или друга"
  - "При создании игры язык программирования НЕ выбирается сразу (отложенная инициализация языка)"
  - "Система предоставляет список активных игр, доступных для подключения (система матчмейкинга/очередь)"
  - "Второй игрок может подключиться к существующей игре по нажатию \"Connect to game\""
  - "Система предоставляет раздельный интерфейс с двумя редакторами кода: слева — свой, справа — соперника"
  - "Код синхронизируется между игроками в реальном времени (видно, что печатает соперник)"
  - "Задание отображается сверху, под ним — таймер игры (позже добавляется чат слева)"
  - "Кнопка \"Check\" доступна для неограниченного количества попыток проверки решения"
  - "Тесты проверки решения запускаются только на локальном коде игрока, не на коде соперника"
  - "Игра длится до первого успешного решения, без принудительного таймера на победу"
  - "Система поддерживает переподключение при разрыве соединения (восстановление сессии по ID)"
  - "При успешной проверке решения показывается модальное окно с определением победителя"
  - "У победителя кнопка \"Check\" блокируется, появляется кнопка \"Exit\", но он может остаться и смотреть код"
  - "Проигравший может продолжать писать и проверять код (но победитель уже определен)"
  - "Игра удаляется из памяти только после выхода обоих игроков"
  - "Пользователь может выбирать задачи из каталога с фильтрацией по сложности и тегам"
  - "Система автоматически проверяет решение через тесты и показывает результат (pass/fail)"
  - "Пользователь видит свой рейтинг (ELO), статистику игр и прогресс"
  - "Пользователь может участвовать в турнирах с призовой системой рейтинговых очков"
  - "Пользователь может общаться с соперником в чате во время игры"

non-functional:
  - "Время ответа системы на действия пользователя не должно превышать 2 секунд"
  - "Синхронизация кода между игроками должна происходить с задержкой менее 500 мс (реализация через WebSocket/аналог, например, Operational Transformation или CRDT)"
  - "Система должна поддерживать до 5000 одновременных активных игр"
  - "Доступность системы (uptime) должна составлять не менее 99.5%"
  - "Код пользователя должен выполняться в изолированных Docker-контейнерах"
  - "Соединение между клиентом и сервером должно использовать защищенные протоколы (WSS для WebSocket)"
  - "Данные игр и решений должны сохраняться в надежном хранилище с регулярным бэкапом"
  - "Система должна использовать WebSocket или аналоги для синхронизации в реальном времени"
  - "Должна быть реализована система восстановления сессий при разрыве соединения"
  - "Интерфейс должен корректно работать в последних версиях основных браузеров"
  - "Мобильная версия интерфейса должна быть адаптивной для экранов от 320px"

implicit:
  - "Интерфейс должен быть интуитивно понятен для программистов разного уровня"
  - "Система должна поддерживать здоровую конкурентную среду без возможности читерства"
  - "Синхронизация кода должна быть плавной, без заметных лагов"
  - "Все пользовательские данные (особенно код решений) должны быть конфиденциальны"
  - "Сессионные данные должны защищаться от несанкционированного доступа"
  - "Система должна быть расширяемой для добавления новых языков программирования и типов задач"
  - "Сообщество должно иметь возможность создавать и публиковать свои задачи через GitHub"
  - "Интеграция с GitHub должна использовать стандартные OAuth-протоколы без хранения паролей"
  - "Система должна четко управлять состояниями игры: active, finished (один победил), closed (оба вышли)"
  - "Игровые сессии должны сохраняться до полного завершения всеми участниками"
  - "Система должна поддерживать отложенную инициализацию языка (язык не жёстко привязан к сессии)"
